INSERT INTO lacecodb.position (`discipline_id`, `position_name`, `level_of_management_id`, `grade_id`)
VALUES
    (9, 'Director of Operations', 1, 3),
    (9, 'Partner', 1, 3),
    (9, 'Design Principal', 1, 3),
    (1, 'Director of Business Development', 2, 5),
    (1, 'Business Development Manager', 3, 6),
    (1, 'Business Development Coordinator', 4, 9),
    (2, 'Marketing Manager', 3, 6),
    (2, 'Senior Graphic Designer', 4, 8),
    (2, 'Senior Marketing Coordinator', 4, 8),
    (2, 'Public Relations Specialist', 4, 9),
    (2, 'Graphic Designer', 4, 9),
    (2, 'Marketing Coordinator', 4, 9),
    (7, 'Contracts Manager', 3, 6),
    (7, 'Head of Contracts', 3, 6),
    (7, 'Contracts Administrator', 4, 8),
    (6, 'Director of Construction', 2, 4),
    (6, 'HSE Manager', 3, 6),
    (6, 'Site Project Manager', 3, 6),
    (6, 'Resident Architect', 3, 6),
    (6, 'Resident Engineer', 3, 6),
    (6, 'Senior Site Project Manager', 3, 6),
    (6, 'Lead Site Architect', 4, 7),
    (6, 'Lead Site Civil Engineer', 4, 7),
    (6, 'Lead Site Electrical Engineer', 4, 7),
    (6, 'Lead Site Mechanical Engineer', 4, 7),
    (6, 'Senior Quantity Surveyor', 4, 8),
    (6, 'Senior Site Architect', 4, 8),
    (6, 'Senior Site Civil Engineer', 4, 8),
    (6, 'Senior Site Electrical Engineer', 4, 8),
    (6, 'Senior Site Mechanical Engineer', 4, 8),
    (6, 'Quantity Surveyor', 4, 9),
    (6, 'Senior Safety Officer', 4, 9),
    (6, 'Site Architect', 4, 9),
    (6, 'Site Civil Engineer', 4, 9),
    (6, 'Site Electrical Engineer', 4, 9),
    (6, 'Site Mechanical Engineer', 4, 9),
    (6, 'Architectural Inspector', 5, 10),
    (6, 'Civil Inspector', 5, 10),
    (6, 'Document Controller', 5, 10),
    (6, 'Electrical Inspector', 5, 10),
    (6, 'Finishing Inspector', 5, 10),
    (6, 'HSE Engineer', 5, 10),
    (6, 'Mechanical Inspector', 5, 10),
    (6, 'Safety Officer', 5, 10),
    (6, 'Senior Architectural Inspector', 5, 10),
    (6, 'Senior Civil Inspector', 5, 10),
    (6, 'Senior Document Controller', 5, 10),
    (6, 'Senior Electrical Inspector', 5, 10),
    (6, 'Senior Finishing Inspector', 5, 10),
    (6, 'Senior Mechanical Inspector', 5, 10),
    (80, 'Head of Architecture', 3, 6),
    (80, 'Lead Architect', 3, 7),
    (80, 'Lead Interior Designer', 3, 7),
    (80, 'Lead Landscape Architect', 3, 7),
    (80, 'Lead Urban Designer', 3, 7),
    (80, 'Senior Architect', 4, 8),
    (80, 'Senior Interior Designer', 4, 8),
    (80, 'Senior Landscape Architect', 4, 8),
    (80, 'Senior Urban Designer', 4, 8),
    (80, 'Architect', 4, 9),
    (80, 'Interior Designer', 4, 9),
    (80, 'Landscape Architect', 4, 9),
    (80, 'Senior Draftsman', 4, 9),
    (80, 'Urban Designer', 4, 9),
    (80, 'Draftsman', 5, 10),
    (80, 'Junior Architect', 5, 10),
    (80, 'Junior Interior Designer', 5, 10),
    (80, 'Junior Landscape Architect', 5, 10),
    (80, 'Junior Urban Designer', 5, 10),
    (60, 'BIM Manager', 4, 8),
    (60, 'BIM Coordinator', 4, 9),
    (61, 'Electrical Engineer', 4, 9),
    (61, 'Head of Electrical', 3, 6),
    (61, 'Lead Electrical Engineer', 3, 7),
    (61, 'Senior Electrical Engineer', 4, 8),
    (61, 'Junior Electrical Engineer', 5, 10),
    (62, 'Director of Engineering', 2, 5),
    (63, 'Head of Environmental', 3, 8),
    (63, 'Lead Environmental Engineer', 3, 7),
    (63, 'Senior Environmental Engineer', 4, 8),
    (63, 'Solid Waste Expert', 4, 8),
    (63, 'Environmental Engineer', 4, 9),
    (63, 'Junior Environmental Engineer', 5, 10),
    (63, 'Forman', 5, 10),
    (80, 'Director Of Design and Advisory', 2, 4),
    (64, 'Head of Mechanical', 3, 6),
    (64, 'Lead Mechanical Engineer', 3, 7),
    (64, 'Senior Mechanical Engineer', 4, 8),
    (64, 'Mechanical Engineer', 4, 9),
    (64, 'Junior Mechanical Engineer', 5, 10),
    (65, 'Head of Proposals', 3, 6),
    (65, 'Lead Proposals Coordinator', 3, 7),
    (65, 'Senior Proposals Coordinator', 4, 8),
    (65, 'Proposals Coordinator', 4, 9),
    (65, 'Junior Proposals Coordinator', 5, 10),
    (66, 'Head of Quantity Surveying', 3, 6),
    (66, 'Lead Quantity Surveyor', 3, 7),
    (66, 'Senior Quantity Surveyor', 4, 8),
    (66, 'Quantity Surveyor', 4, 9),
    (66, 'Junior Quantity Surveyor', 5, 10),
    (67, 'Head of Road & Transportation Engineer', 3, 6),
    (67, 'Lead Road & Transportation Engineer', 3, 7),
    (67, 'Senior Road & Transportation Engineer', 4, 8),
    (67, 'Road & Transportation Engineer', 4, 9),
    (67, 'Junior Road & Transportation Engineer', 5, 10),
    (68, 'Head of Structure', 3, 6),
    (68, 'Lead Structural Engineer', 3, 7),
    (68, 'Senior Structural Engineer', 4, 8),
    (68, 'Structural Engineer', 4, 9),
    (68, 'Junior Structural Engineer', 5, 10),
    (69, 'Head of Wet Utilities', 3, 6),
     (69, 'Lead Wet Infrastructure Utilities Engineer', 3, 7),
      (69, 'Senior Wet Infrastructure Utilities Engineer', 4, 8),
(69, 'Wet Infrastructure Utilities Engineer', 4, 9),
(69, 'Junior Wet Infrastructure Utilities Engineer', 5, 10),
(70, 'Chief Executive Officer', 1, 3),
(71, 'Director of Finance', 2, 5),
(71, 'Senior Accountant', 4, 8),
(71, 'Accountant', 4, 9),
(71, 'Junior Accountant', 5, 10),
(72, 'Organizational Performance Lead', 3, 6),
(73, 'Developer', 4, 9),
(73, 'Planning Engineer', 4, 9),
(74, 'Administrative Manager', 4, 8),
(74, 'Office Manager', 4, 9),
(74, 'Administrative Assistant', 5, 10),
(74, 'Receptionist', 5, 10),
(74, 'Driver', 7, 11),
(74, 'Office Boy', 7, 11),
(74, 'PRO', 7, 11),
(75, 'IT Manager', 3, 7),
(75, 'Plotting Officer', 5, 10),
(75, 'Senior Software Developer', 4, 8),
(75, 'Senior System Administrator', 4, 8),
(75, 'Software Developer', 4, 9),
(75, 'Junior Software Developer', 5, 10),
(75, 'System Administrator', 4, 9),
(75, 'Junior System Administrator', 5, 10),
(76, 'Director of HR and OD', 2, 4),
(77, 'Senior Human Resource Coordinator', 4, 8),
(77, 'Senior Human Resource Officer', 4, 8),
(77, 'Senior Recruitment Coordinator', 4, 8),
(77, 'HR Business Partner', 4, 8),
(77, 'Senior Compensation and Benefits Officer', 4, 8),
(77, 'Human Resource Coordinator', 4, 9),
(77, 'Human Resource Officer', 4, 9),
(77, 'Recruitment Coordinator', 4, 9),
(77, 'Compensation and Benefits Officer', 4, 9),
(78, 'Senior Project Manager', 3, 6),
(78, 'Project Manager', 3, 7),
(78, 'PMU Coordinator', 4, 9);